apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mmdung-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SadPenguin1/ci-cd-helm-repo
    targetRevision: HEAD
    path: helm/microservice
  destination:
    server: https://kubernetes.default.svc
    namespace: nmdung-helm
  syncPolicy:
    automated:
      prune: true
