apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cd-helm-multiple-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SadPenguin1/ci-cd-helm-repo
    targetRevision: HEAD
    path: helm/helmfile.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ci-cd-helm
  syncPolicy:
    automated:
      prune: true
