apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cd-helm
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/SadPenguin1/ci-cd-helm-repo
    targetRevision: HEAD
    path: helm
  destination:
    server : https://kubernetes.default.svc
    namespace : ci-cd-helm
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

