apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-deploy  
  namespace: {{ .Release.Namespace }}
  labels:
    app: config-service-deploy
spec:
  replicas: {{ .Values.replicaCount }}  
  selector:
    matchLabels:
      app: config-service-deploy
  template:
    metadata:
      labels:
        app: config-service-deploy
    spec:
      containers:
      - name: config-service-container
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}  
        imagePullPolicy: {{ .Values.image.pullPolicy }}  
        ports:
        - containerPort: {{ .Values.service.port }}  