configservice:
  replicaCount: 1
  image:
    repository: nguyenmanhdung/config-service
    tag: 0.2.0
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8888
    targetPort: 8888
    nodePort: 30021
  namespace: ci-cd-helm


discoveryservice:
  replicaCount: 1
  image:
    repository: nguyenmanhdung/discovery-service
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    port: 8761
    targetPort: 8761
    namespace: ci-cd-helm


monitorservice:
  replicaCount: 1
  image:
    repository: nguyenmanhdung/monitor-admin
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    port: 8086
    targetPort: 8086
    namespace: ci-cd-helm

gatewayservice:
  replicaCount: 1
  image:
    repository: nguyenmanhdung/gateway-service
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    port: 8085
    targetPort: 8085
    namespace: ci-cd-helm


zipkinservice:
  replicaCount: 1
  image:
    repository: nguyenmanhdung/zipkin
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    port: 9411
    targetPort: 9411
    namespace: ci-cd-helm


mysql:
  replicaCount: 1
  image:
    repository: mysql
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 3306
    targetPort: 3306
    namespace: ci-cd-helm


authservice:
  replicaCount: 1
  image:
    repository: nguyenmanhdung/auth-service
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    port: 8082
    targetPort: 8082
    namespace: ci-cd-helm

userservice:
  replicaCount: 1
  image:
    repository: nguyenmanhdung/user-service
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    port: 8087
    targetPort: 8087
    namespace: ci-cd-helm


notificationservice:
  replicaCount: 1
  image:
    repository: nguyenmanhdung/notification-service
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    port: 8084
    targetPort: 8084
    namespace: ci-cd-helm


statisticservice:
  replicaCount: 1
  image:
    repository: nguyenmanhdung/statistic1-service
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    port: 8088
    targetPort: 8088
    namespace: ci-cd-helm







