apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ci-cd-helm
  namespace: nmdung-helm  
spec:
  ingressClassName: nginx
  rules:
    - host: nmdung-helm.devops.vn
      http:
        paths:
          - path: /config
            pathType: Prefix
            backend:
              service:
                name: config-service-service
                port:
                  number: 8888
          - path: /monitor-service
            pathType: Prefix
            backend:
              service:
                name: monitor-service-service
                port:
                  number: 8086

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-discovery
  namespace: nmdung-helm  
spec:
  ingressClassName: nginx
  rules:
    - host: nmdung-helm.devops.vn
      http:
        paths:
          - path: /discovery
            pathType: Prefix
            backend:
              service:
                name: discovery-service-service
                port:
                  number: 8761
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-user
  namespace: nmdung-helm  
spec:
  ingressClassName: nginx
  rules:
    - host: nmdung-helm.devops.vn
      http:
        paths:
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: user-service-service
                port:
                  number: 8087


