apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-config-helm
  namespace: nmdung-helm
  annotations:
spec:
  ingressClassName: nginx
  rules:
    - host: nmdung-helm.devops.vn
      http:
        paths:
          - path: /config
            pathType: Prefix
            backend:
              service:
                name: config-service-service
                port:
                  number: 8888
          - path: /zipkin
            pathType: Prefix
            backend:
              service:
                name: zipkin-service-service
                port:
                  number: 9411
          - path: /monitor
            pathType: Prefix
            backend:
              service:
                name: monitor-service-service
                port:
                  number: 8086

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-monitor-helm
  namespace: nmdung-helm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: nmdung-monitor.devops.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitor-service-service
                port:
                  number: 8086
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-discovery-helm
  namespace: nmdung-helm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: nmdung-discovery.devops.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: discovery-service-service
                port:
                  number: 8761
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-user-helm
  namespace: nmdung-helm
  annotations:
spec:
  ingressClassName: nginx
  rules:
    - host: nmdung-user.devops.vn
      http:
        paths:
          - path: /        
            pathType: Prefix
            backend:
              service:
                name: user-service-service
                port:
                  number: 8087
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-notification-helm
  namespace: nmdung-helm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: nmdung-notification.devops.vn
      http:
        paths:
          - path: /        
            pathType: Prefix
            backend:
              service:
                name: notification-service-service
                port:
                  number: 8084

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-auth-helm
  namespace: nmdung-helm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: nmdung-auth.devops.vn
      http:
        paths:
          - path: /        
            pathType: Prefix
            backend:
              service:
                name: auth-service-service
                port:
                  number: 8082
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-statistic-helm
  namespace: nmdung-helm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: nmdung-statistic.devops.vn
      http:
        paths:
          - path: /        
            pathType: Prefix
            backend:
              service:
                name: statistic-service-service
                port:
                  number: 8088
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gateway-helm
  namespace: nmdung-helm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: nmdung-gateway.devops.vn
      http:
        paths:
          - path: /        
            pathType: Prefix
            backend:
              service:
                name: gateway-service-service
                port:
                  number: 8085




