apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ci-cd-helm
  namespace: ci-cd-helm   
spec:
  rules:
    - host: microservice-helm
      http:
        paths:
          - path: /config-service
            pathType: Prefix
            backend:
              service:
                name: config-service-service
                port:
                  number: 8888
          - path: /discovery-service
            pathType: Prefix
            backend:
              service:
                name: discovery-service-service
                port:
                  number: 8761
  tls:
    - hosts:
        - microservice-helm
      secretName: example-tls-secret
