apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-config-helm
  namespace: nmdung-helm
  annotations:
spec:
  ingressClassName: nginx
  rules:
    - host: nmdung-helm.devops.vn
      http:
        paths:
          - path: /config
            pathType: Prefix
            backend:
              service:
                name: config-service-service
                port:
                  number: 8888

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-monitor-helm
  namespace: nmdung-helm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: nmdung-helm.devops.vn
      http:
        paths:
          - path: /monitor
            pathType: Prefix
            backend:
              service:
                name: monitor-service-service
                port:
                  number: 8086
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-discovery-helm
  namespace: nmdung-helm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: nmdung-helm.devops.vn
      http:
        paths:
          - path: /discovery
            pathType: Prefix
            backend:
              service:
                name: discovery-service-service
                port:
                  number: 8761
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-user-helm
  namespace: nmdung-helm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /swagger-ui/index.html
spec:
  ingressClassName: nginx
  rules:
    - host: nmdung-helm.devops.vn
      http:
        paths:
          - path: /user        
            pathType: Prefix
            backend:
              service:
                name: user-service-service
                port:
                  number: 8087
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-notification-helm
  namespace: nmdung-helm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: nmdung-helm.devops.vn
      http:
        paths:
          - path: /notification        
            pathType: Prefix
            backend:
              service:
                name: notification-service-service
                port:
                  number: 8084
    


