apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ci-cd-helm
  namespace: nmdung-helm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: nmdung-helm.devops.vn
      http:
        paths:
          - path: /config
            pathType: Prefix
            backend:
              service:
                name: config-service-service
                port:
                  number: 8888
          - path: /monitor
            pathType: Prefix
            backend:
              service:
                name: monitor-service-service
                port:
                  number: 8086
          - path: /discovery
            pathType: Prefix
            backend:
              service:
                name: discovery-service-service
                port:
                  number: 8761
          - path: /user         
            pathType: Prefix
            backend:
              service:
                name: user-service-service
                port:
                  number: 8087
    


