apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql  
  namespace: {{ .Release.Namespace }}
  labels:
    app: mysql
spec:
  replicas: {{ .Values.mysql.replicaCount }}  
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}  
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}  
        ports:
        - containerPort: {{ .Values.mysql.service.port }}  
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.service.port }}  
      targetPort: {{ .Values.mysql.service.targetPort }}  

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myspl-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: low-latency-mysql
  hostPath:
    path: /tmp

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: low-latency-mysql
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: low-latency-mysql
  namespace: {{ .Release.Namespace }}
provisioner: csi-driver.example-vendor.example
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - discard
volumeBindingMode: WaitForFirstConsumer
parameters:
  guaranteedReadWriteLatency: "true"




