apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-ci-cd
  namespace: ci-cd-helm  
provisioner: rancher.io/local-path
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - discard
volumeBindingMode: WaitForFirstConsumer
parameters:
  guaranteedReadWriteLatency: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ci-cd-helm
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mysql
spec:
 selector:
   matchLabels:
     app: mysql
 serviceName: mysql
 replicas: 1
 template:
   metadata:
     labels:
       app: mysql
   spec:
     terminationGracePeriodSeconds: 10
     containers:
     - name: mysql
       image: mysql:latest
       ports:
       - containerPort: 3306
         name: mysql
       env:
       - name: MYSQL_ROOT_PASSWORD
         valueFrom:
           secretKeyRef:
             name: mysql-secret
             key: MYSQL_ROOT_PASSWORD
       volumeMounts:
       - mountPath: /var/lib/mysql
         name: mysql-pv-volume
 volumeClaimTemplates:
 - metadata:
     name: mysql-pvc
   spec:
     storageClassName: sc-ci-cd
     accessModes: [ "ReadWriteOnce" ]
     resources:
       requests:
         storage: 2Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
